import { useState, useEffect } from 'react';
import { apiFetch } from '../utils/api';

interface GeneratedDocument {
  id: string;
  type: 'QUOTE' | 'JOB_SHEET' | 'COMPLETION_REPORT';
  presignedUrl?: string; // We can fetch this via /documents/:id/url
  createdAt: string;
  generatedBy?: { name: string };
}

export function JobDocuments({ jobId }: { jobId: string }) {
  const [docs, setDocs] = useState<GeneratedDocument[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    loadDocs();
  }, [jobId]);

  const loadDocs = async () => {
    try {
      // The backend includes generatedDocuments in the /jobs/:id payload now
      const jobData = await apiFetch(`/jobs/${jobId}`);
      setDocs(jobData.generatedDocuments || []);
    } catch (err: any) {
      setError('Failed to load documents.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerate = async (type: 'QUOTE' | 'JOB_SHEET' | 'COMPLETION_REPORT') => {
    setIsGenerating(true);
    setError('');
    
    // Map type to endpoint path
    let endpoint = '';
    if (type === 'QUOTE') endpoint = '/documents/quote';
    if (type === 'JOB_SHEET') endpoint = '/documents/job-sheet';
    if (type === 'COMPLETION_REPORT') endpoint = '/documents/completion-report';

    try {
      const newDoc = await apiFetch(endpoint, {
        method: 'POST',
        body: JSON.stringify({ jobId })
      });
      setDocs([newDoc, ...docs]);
    } catch (err: any) {
      setError(err.message || `Failed to generate ${type}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const getDocUrl = async (id: string, index: number) => {
    try {
      const response = await apiFetch(`/documents/${id}/url`);
      const newDocs = [...docs];
      newDocs[index].presignedUrl = response.url;
      setDocs(newDocs);
      window.open(response.url, '_blank');
    } catch (err) {
      alert('Failed to get document URL');
    }
  };

  return (
    <div style={{ background: 'var(--surface-color)', padding: 'var(--spacing-md)', borderRadius: 'var(--border-radius)', border: '1px solid var(--border-color)', marginTop: 'var(--spacing-md)' }}>
      <h3 style={{ fontSize: '1rem', borderBottom: '1px solid var(--border-color)', paddingBottom: 'var(--spacing-sm)', marginBottom: 'var(--spacing-sm)' }}>Documents (PDF)</h3>
      
      {error && <div style={{ color: 'var(--status-cancelled-text)', marginBottom: 'var(--spacing-sm)' }}>{error}</div>}

      <div style={{ display: 'flex', gap: 'var(--spacing-sm)', marginBottom: 'var(--spacing-md)' }}>
        <button onClick={() => handleGenerate('QUOTE')} disabled={isGenerating} className="primary">Generate Quote</button>
        <button onClick={() => handleGenerate('JOB_SHEET')} disabled={isGenerating} className="primary">Generate Job Sheet</button>
        <button onClick={() => handleGenerate('COMPLETION_REPORT')} disabled={isGenerating} className="primary">Generate Completion Report</button>
        {isGenerating && <span style={{ display: 'flex', alignItems: 'center', color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Generating PDF...</span>}
      </div>

      {isLoading ? <p>Loading documents...</p> : (
        <table className="dense-table" style={{ fontSize: '0.85rem' }}>
          <thead>
            <tr>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {docs.map((doc, index) => (
              <tr key={doc.id}>
                <td style={{ fontWeight: 600 }}>{doc.type.replace(/_/g, ' ')}</td>
                <td>{doc.generatedBy?.name || 'Unknown'}</td>
                <td className="tabular-nums">{new Date(doc.createdAt).toLocaleString()}</td>
                <td>
                  {doc.presignedUrl ? (
                    <a href={doc.presignedUrl} target="_blank" rel="noreferrer" style={{ color: 'var(--status-checked-text)', fontWeight: 600 }}>
                      View / Download PDF
                    </a>
                  ) : (
                    <button onClick={() => getDocUrl(doc.id, index)} className="secondary" style={{ padding: '0.2rem 0.5rem', fontSize: '0.75rem' }}>
                      Get Link
                    </button>
                  )}
                </td>
              </tr>
            ))}
            {docs.length === 0 && (
              <tr>
                <td colSpan={4} style={{ textAlign: 'center' }}>No documents generated yet.</td>
              </tr>
            )}
          </tbody>
        </table>
      )}
    </div>
  );
}
